[package]
name = "haridokei"
version = "0.2.0"
edition = "2024"
license = "MIT"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit", "wayland", "x11"] }
log = "0.4.29"
systemd-journal-logger = "2.2.2"
image = "0.25"
imageproc = "0.27"
ab_glyph = "0.2.32"
chrono = { version = "0.4.44", features = ["clock"] }
clap = { version = "4.6.1", features = ["derive"] }
daemonize = "0.5.0"
confy = "2.0.0"
serde = { version = "1.0.228", features = ["derive", "serde_derive"] }
sd-notify = "0.5.0"
signal-hook = "0.4.4"
anyhow = "1.0.102"
